### ISSUE TITLE
Lambda symbol causing "CEUnboundVar" failure

### ISSUE THREAD

**Issue by sackeyjason** [ChickenProp/haskenthetical#1]
I've run into a problem getting the examples running. I installed stack, and the build command seemed to work fine.

`stack exec -- haskenthe -h` prints out help to the terminal.

I tried `stack exec -- haskenthe examples/factorial.hth`, resulting in:

```
failed
CEUnboundVar (Name "\9580\9559")
```

I dug around and found that \9580\9559 seems to represent the lambda character in the code. Code without lambda runs fine.

Now, if I do this: `$ stack exec -- haskenthe --print-expr ./examples/factorial.hth`

result:

```
[Def
   fac
   (Call
      (Call (Var ╬╗) (Var x))
      (IfMatch
         (Var x)
         (PatLiteral 0.0)
         (Val 1.0)
         (Call
            (Call (Var *) (Var x))
            (Call (Var fac) (Call (Call (Var `-`) (Var x)) (Val 1.0)))))),
 Call (Var fac) (Val 5.0)]

failed
CEUnboundVar (Name "\9580\9559")
```

Something seems to have replaced the lambda with this strange "╬╗" string. That = "\9580\9559".

Possible source of the issue is me trying to run this on Windows. Maybe while doing the git clone, it converted code into an incompatible encoding format or something. The hth files are in UTF-8, which seems normal enough.

Any help/ideas appreciated.

**Comment by ChickenProp** [comment]
Interesting! This sort of thing is probably part of why no real language uses unicode syntax.

That seems to be two box-drawing characters. The relevant codepoints are: [λ](https://www.fileformat.info/info/unicode/char/3bb/index.htm) [╬](https://www.fileformat.info/info/unicode/char/256c/index.htm) [╗](https://www.fileformat.info/info/unicode/char/2557/index.htm). I can't immediately see any connection that suggests how this would have happened.

If you're able to do a hexdump (on linux, that would be the commands `hexdump` or `xxd`), it would be helpful to confirm that the λs in the .hth files are indeed represented by the byte sequence CEBB, and that there's nothing outside the ascii range at the beginning of the file. I'm not really expecting those to be the problem, but good to cover all bases.

I think my most likely guess is that this is a locale thing. If you have access to ghci (possibly through `stack ghci`), running

    import GHC.IO.Encoding
    getLocaleEncoding
    getFileSystemEncoding
    getForeignEncoding

in that might turn up something. (https://hackage.haskell.org/package/base-4.12.0.0/docs/GHC-IO-Encoding.html suggests that getFileSystemEncoding at least shouldn't be relevant on windows, but I don't know how seriously to take that.)

**Comment by sackeyjason** [comment]
It would be a shame if this sort of thing prevents languages from using more non-ascii characters forever. I did an xxd:

```
$ xxd examples/factorial.hth
00000000: 2864 6566 2066 6163 0d0a 2020 28ce bb20  (def fac..  (..
00000010: 780d 0a20 2020 2028 6966 7e20 7820 300d  x..    (if~ x 0.
00000020: 0a20 2020 2020 2031 0d0a 2020 2020 2020  .      1..
00000030: 282a 2078 2028 6661 6320 282d 2078 2031  (* x (fac (- x 1
00000040: 2929 2929 2929 0d0a 2866 6163 2035 290d  ))))))..(fac 5).
00000050: 0a                                       .
```

So lambda is indeed represented as "CEBB" here.

I did the `stack ghci` commands, and for all the gets I got "CP850". https://en.wikipedia.org/wiki/Code_page_850 - this must be the issue. We want Unicode, not this.

Going to install cygwin now.

**Comment by ChickenProp** [comment]
Okay! Can you try out #2 and see if it works? You might also want to try it passing in the program with `-e`.

**Comment by sackeyjason** [comment]
Using -e works! That lets me try it out at least.

Trying to fun factorial.hth still has the same ╬╗ problem.

(And running it in cygwin didn't change anything.)

**Comment by ChickenProp** [comment]
Huh, weird. I just pushed a version that tries harder and includes some debugging output, could you try that?

**Comment by sackeyjason** [comment]
It works! Here's the output:

```
$ stack exec -- haskenthe examples/factorial.hth
CP850
CP850
CP850
UTF-8
UTF-8
UTF-8
Just UTF-8
Literal (Float 120.0)
```

**Comment by ChickenProp** [comment]
Excellent! Can you try different combinations of the `set*Encoding` lines and see which ones are necessary? (And whether any have an effect on `-e`?) Given that `setFileSystemEncoding` by itself didn't work, my guess would be you either need only `setLocaleEncoding`, or both `setLocaleEncoding` and `setFileSystemEncoding`; and `setForeignEncoding` would be having no effect right now.

**Comment by sackeyjason** [comment]
Seems only `Encoding.setLocaleEncoding Encoding.utf8` is needed. Works with -e and with loading hth files.

**Comment by ChickenProp** [comment]
Great, thanks! Seems I misunderstood what `setFileSystemEncoding` does.
